# Generated by Django 5.0.3 on 2024-03-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODENAME', models.CharField(max_length=100)),
                ('GUNAME', models.CharField(max_length=100)),
                ('TITLE', models.CharField(max_length=255)),
                ('DATE', models.CharField(max_length=100)),
                ('PLACE', models.CharField(max_length=255)),
                ('ORG_NAME', models.CharField(max_length=100)),
                ('USE_TRGT', models.CharField(max_length=255)),
                ('USE_FEE', models.CharField(max_length=100)),
                ('PLAYER', models.TextField()),
                ('PROGRAM', models.TextField()),
                ('ETC_DESC', models.TextField()),
                ('ORG_LINK', models.URLField()),
                ('MAIN_IMG', models.URLField()),
                ('RGSTDATE', models.DateField()),
                ('TICKET', models.CharField(max_length=50)),
                ('STRTDATE', models.DateField()),
                ('END_DATE', models.DateField()),
                ('THEMECODE', models.CharField(max_length=50)),
                ('LOT', models.FloatField()),
                ('LAT', models.FloatField()),
                ('IS_FREE', models.CharField(max_length=200)),
                ('HMPG_ADDR', models.URLField()),
            ],
        ),
    ]
